In [1]:
import numpy as np

class TicTacToe:
    def __init__(self, grid_size):
        self.size = grid_size
        self.grid = np.zeros((grid_size, grid_size))
        self.valid_plays = [(i, j) for i, row in enumerate(self.grid) 
                            for j, value in enumerate(row) if value == 0]
    
    def play(self, player, position):
        
        if player not in [-1,1]:
            print('Player not allowed')
            return
        
        if self.check_status() == 1:
            print('The game is over')
            return
        
        if position not in self.valid_plays:
            print('Play not allowed! Try again')
            return
        
        if np.sum(self.grid == -1) == np.sum(self.grid == 1) + 1 and player == 0:
            print('Player 0 cannot play twice in a row')
            return
        
        if np.sum(self.grid == 1) == np.sum(self.grid == -1) and player == 1:
            print('Player 1 cannot play twice in a row')
            return
        
        self.grid[position] = player
        self.valid_plays.remove(position)
        
        if self.check_status():
            print(f'Player {player} Won')
            return 
        
    def check_status(self):
        
        val = len(self.grid)
        if val in np.sum(self.grid, axis = 0) or -val in np.sum(self.grid, axis = 0):
            print(val)
            print('VERTICAL WIN')
            return 1
        
        if val in np.sum(self.grid, axis = 1) or -val in np.sum(self.grid, axis = 1):
            print('HORIZONTAL WIN')
            return 1
        
        if np.trace(self.grid) == val or np.trace(self.grid) == -val:
            print('DIAGONAL WIN')
            return 1
        
        if np.trace(np.fliplr(self.grid)) == val or np.trace(np.fliplr(self.grid)) == -val:
            print('DIAGONAL WIN')
            return 1

        return 0
    
    def display_board(self):

        for i, row in enumerate(self.grid):

            row_display = " | ".join('X' if cell == 1 else 'O' if cell == -1 else ' ' for cell in row)
            
            print(" " + row_display + " ")

            if i < len(self.grid) - 1:
                print("---+" * (self.size - 1) + "---")
            
            
            

In [2]:
a = TicTacToe(5)

In [3]:
print(a.grid)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
a.play(-1, (0, 0))

In [5]:
a.grid

array([[-1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [6]:
a.display_board()

 O |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   


In [7]:
a.play(1, (1,1))

In [8]:
a.display_board()

 O |   |   |   |   
---+---+---+---+---
   | X |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   


In [9]:
a.play(-1, (0,2))

In [10]:
a.play(1, (2,2))

In [11]:
a.display_board()

 O |   | O |   |   
---+---+---+---+---
   | X |   |   |   
---+---+---+---+---
   |   | X |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   


In [12]:
a.play(-1, (0, 1))

In [13]:
a.display_board()

 O | O | O |   |   
---+---+---+---+---
   | X |   |   |   
---+---+---+---+---
   |   | X |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   


In [61]:
grid = np.array([[1, -1, 0],
        [0, 0, 0],
        [0, 0, 0]])

seen_grids = [np.array([[0, -1, 1],
               [0, 0, 0],
               [0, 0, 0]])]

check_doubles(grid, seen_grids)

1

In [64]:
def build_symmetry_class(grid):
    cls = [grid,
                  np.rot90(grid, k=1),
                  np.rot90(grid, k=2),
                  np.rot90(grid, k=3),
                  grid.T,
                  np.rot90(grid.T, k=1),
                  np.rot90(grid.T, k=2),
                  np.rot90(grid.T, k=3)]
    return cls

def check_doubles(grid, seen_grids):
    for element in seen_grids:
        if any(np.array_equal(grid, candidate) for candidate in build_symmetry_class(element)):
            return 1
    return 0

    
    
def compute_possible_boards(grid, possible_grids):
    
    if np.sum(grid == 0) == 0:
        possible_grids.append(grid)
        print('GAME ALREADY OVER 1')
        return 
    val = len(grid)
    if val in np.sum(grid, axis = 0) or -val in np.sum(grid, axis = 0):
        possible_grids.append(grid)
        print('GAME ALREADY OVER 2')
        return
        
    
    if val in np.sum(grid, axis = 1) or -val in np.sum(grid, axis = 1):
        possible_grids.append(grid)
        print('GAME ALREADY OVER 3')
        return
        
    
    if np.trace(grid) == val or np.trace(grid) == -val:
        possible_grids.append(grid)
        print('GAME ALREADY OVER 4')
        return
        
    
    if np.trace(np.fliplr(grid)) == val or np.trace(np.fliplr(grid)) == -val:
        possible_grids.append(grid)
        print('GAME ALREADY OVER 5')
        return
        

    if np.sum(grid == -1) == np.sum(grid == 1):
        player = -1
    else:
        player = 1
    rows, cols = np.where(grid == 0)
    
    target_zero_count = np.count_nonzero(grid == 0) - 1

    sublist = [arr for arr in possible_grids if np.count_nonzero(arr == 0) == target_zero_count]
    
    for r, c in zip(rows, cols):
        new_grid = grid.copy()
        new_grid[r, c] = player
        if not check_doubles(new_grid, sublist):
            compute_possible_boards(new_grid, possible_grids)
        
    return possible_grids
    
        

In [65]:
grid = np.array([[0, 0, 0], 
                [0, 0, 0],
                [0, 0, 0]])
possible_grids = compute_possible_boards(grid, [])
possible_grids

GAME ALREADY OVER 5
GAME ALREADY OVER 1
GAME ALREADY OVER 4
GAME ALREADY OVER 1
GAME ALREADY OVER 1
GAME ALREADY OVER 4
GAME ALREADY OVER 4
GAME ALREADY OVER 5
GAME ALREADY OVER 2
GAME ALREADY OVER 1
GAME ALREADY OVER 1
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 3
GAME ALREADY OVER 2
GAME ALREADY OVER 1
GAME ALREADY OVER 2
GAME ALREADY OVER 1
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 3
GAME ALREADY OVER 3
GAME ALREADY OVER 4
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 1
GAME ALREADY OVER 2
GAME ALREADY OVER 4
GAME ALREADY OVER 3
GAME ALREADY OVER 1
GAME ALREADY OVER 4
GAME ALREADY OVER 3
GAME ALREADY OVER 2
GAME ALREADY OVER 4
GAME ALREADY OVER 3
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 5
GAME ALREADY OVER 1
GAME ALREADY OVER 5
GAME ALREADY OVER 2
GAME ALREADY OVER 1
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 2
GAME ALREADY OVER 1


KeyboardInterrupt: 

In [373]:
def create_win_grids(size=3):
    winning_masks = []
    
    # Win over rows
    for row in range(size):
        mask = 0
        for col in range(size):
            mask += 1 << (row * size + col)
        winning_masks.append(mask) 
      
    # Win over columns  
    for col in range(size):
        mask = 0
        for row in range(size):
            mask += 1 << (row * size + col)
        winning_masks.append(mask) 
    
    # Win over main diag
    mask = 0
    for row in range(size):
        mask += 1 << (row * size + row)
    winning_masks.append(mask)
    # Win over anti diag
    mask = 0
    for row in range(size):
        mask += 1 << (row * size + (size - row - 1))
    winning_masks.append(mask)
    
    return winning_masks

winning_configurations = create_win_grids(size=3)

def is_win(grid, winning_configurations):
    player_1, player_2 = grid
    for config in winning_configurations:
        if (player_1 & config) == config:
            #print(1)
            return 1
        if (player_2 & config) == config:
            #print(2)
            return 1
    return 0


def is_full(grid, size):
    conf1, conf2 = grid
    if (conf1 | conf2) == (1 << (size * size)) - 1:
        return 1
    return 0


def play_move(grid, player, move):
    if (grid[0] | grid[1]) & (1 << move) != 0:
        print('MOVE NOT ALLOWED')
        return None
    if player == 0:
        return (grid[0] | (1 << move), grid[1])
    else:
        return (grid[0], grid[1] | (1 << move))
        

In [375]:
def compute_possible_grids(grid, player, possible_grids = None, seen_by_moves = None, size = 3):
    
    if possible_grids is None:
        possible_grids = []
    
    if seen_by_moves is None:
        seen_by_moves = {i: set() for i in range(size * size + 1)}
    
    #grid = canonical_form_bit(grid, size)
    
    conf1, conf2 = grid   
    n_moves = bin(conf1 | conf2).count('1')
    
    if grid in seen_by_moves[n_moves]:
        return possible_grids
    
    
    seen_by_moves[n_moves].add(grid)
    
    if is_win(grid, winning_configurations):
        possible_grids.append(grid)
        return possible_grids
    
    if is_full(grid, size):
        possible_grids.append(grid)
        return possible_grids
    
    for move in range(size ** 2):
        if (conf1 | conf2) & (1 << move) != 0:
            continue
        new_grid = play_move(grid, player, move)
        
        if new_grid is None:
            continue
        compute_possible_grids(new_grid, 1 - player, possible_grids, seen_by_moves, size)
    

    return possible_grids
        
    
    

In [376]:
size = 4
winning_configurations = create_win_grids(size=size)
a = compute_possible_grids((0, 0), 0, None, None, size)

In [377]:
len(a)

659392

In [378]:
def compute_possible_grids_with_dict(grid, player, possible_grids = None, seen_by_moves = None, size = 3):
    
    if possible_grids is None:
        possible_grids = []
    
    if seen_by_moves is None:
        seen_by_moves = {i: dict() for i in range(size * size + 1)}
        
    conf1, conf2 = grid   
    n_moves = bin(conf1 | conf2).count('1')
    
    if grid in seen_by_moves[n_moves]:
        return seen_by_moves
    
    seen_by_moves[n_moves][grid] = (None, None)
    
    if is_win(grid, winning_configurations):
        possible_grids.append(grid)
        seen_by_moves[n_moves][grid] = (None, -1)
        return seen_by_moves
    
    if is_full(grid, size):
        possible_grids.append(grid)
        seen_by_moves[n_moves][grid] = (None, 0)
        return seen_by_moves
    
    current_best_score = -1
    current_best_move = None
    for move in range(size ** 2):
        if (conf1 | conf2) & (1 << move) != 0:
            continue
        new_grid = play_move(grid, player, move)
        
        if new_grid is None:
            continue
        seen_by_moves = compute_possible_grids_with_dict(new_grid, 1 - player, possible_grids, seen_by_moves, size)
        
        move_score = - seen_by_moves[n_moves + 1][new_grid][1]
        if move_score > current_best_score:
            current_best_score = move_score
            current_best_move = move
    seen_by_moves[n_moves][grid] = (current_best_move, current_best_score)

    return seen_by_moves
        

In [381]:
size = 4
winning_configurations = create_win_grids(size=size)
a = compute_possible_grids_with_dict((0, 0), 0, None, None, size)

In [382]:
a

{0: {(0, 0): (0, 0)},
 1: {(1, 0): (1, 0),
  (2, 0): (0, 0),
  (4, 0): (0, 0),
  (8, 0): (0, 0),
  (16, 0): (0, 0),
  (32, 0): (0, 0),
  (64, 0): (0, 0),
  (128, 0): (0, 0),
  (256, 0): (0, 0),
  (512, 0): (0, 0),
  (1024, 0): (0, 0),
  (2048, 0): (0, 0),
  (4096, 0): (0, 0),
  (8192, 0): (0, 0),
  (16384, 0): (0, 0),
  (32768, 0): (0, 0)},
 2: {(1, 2): (2, 0),
  (1, 4): (1, 0),
  (1, 8): (1, 0),
  (1, 16): (1, 0),
  (1, 32): (1, 0),
  (1, 64): (1, 0),
  (1, 128): (1, 0),
  (1, 256): (1, 0),
  (1, 512): (1, 0),
  (1, 1024): (1, 0),
  (1, 2048): (1, 0),
  (1, 4096): (1, 0),
  (1, 8192): (1, 0),
  (1, 16384): (1, 0),
  (1, 32768): (1, 0),
  (2, 1): (2, 0),
  (2, 4): (0, 0),
  (2, 8): (0, 0),
  (2, 16): (0, 0),
  (2, 32): (0, 0),
  (2, 64): (0, 0),
  (2, 128): (0, 0),
  (2, 256): (0, 0),
  (2, 512): (0, 0),
  (2, 1024): (0, 0),
  (2, 2048): (0, 0),
  (2, 4096): (0, 0),
  (2, 8192): (0, 0),
  (2, 16384): (0, 0),
  (2, 32768): (0, 0),
  (4, 1): (1, 0),
  (4, 2): (0, 0),
  (4, 8): (0, 0),
  