In [54]:
import numpy as np

class TicTacToe:
    def __init__(self, grid_size):
        self.size = grid_size
        self.grid = np.zeros((grid_size, grid_size))
        self.valid_plays = [(i, j) for i, row in enumerate(self.grid) 
                            for j, value in enumerate(row) if value == 0]
    
    def play(self, player, position):
        
        if player not in [-1,1]:
            print('Player not allowed')
            return
        
        if self.check_status() == 1:
            print('The game is over')
            return
        
        if position not in self.valid_plays:
            print('Play not allowed! Try again')
            return
        
        if np.sum(self.grid == -1) == np.sum(self.grid == 1) + 1 and player == 0:
            print('Player 0 cannot play twice in a row')
            return
        
        if np.sum(self.grid == 1) == np.sum(self.grid == -1) and player == 1:
            print('Player 1 cannot play twice in a row')
            return
        
        self.grid[position] = player
        self.valid_plays.remove(position)
        
        if self.check_status():
            print(f'Player {player} Won')
            return 
        
    def check_status(self):
        
        val = len(self.grid)
        if val in np.sum(self.grid, axis = 0) or -val in np.sum(self.grid, axis = 0):
            print(val)
            print('VERTICAL WIN')
            return 1
        
        if val in np.sum(self.grid, axis = 1) or -val in np.sum(self.grid, axis = 1):
            print('HORIZONTAL WIN')
            return 1
        
        if np.trace(self.grid) == val or np.trace(self.grid) == -val:
            print('DIAGONAL WIN')
            return 1
        
        if np.trace(np.fliplr(self.grid)) == val or np.trace(np.fliplr(self.grid)) == -val:
            print('DIAGONAL WIN')
            return 1

        return 0
    
    def display_board(self):

        for i, row in enumerate(self.grid):

            row_display = " | ".join('X' if cell == 1 else 'O' if cell == -1 else ' ' for cell in row)
            
            print(" " + row_display + " ")

            if i < len(self.grid) - 1:
                print("---+" * (self.size - 1) + "---")
            
            
            

In [67]:
a = TicTacToe(5)

In [68]:
print(a.grid)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [69]:
a.play(-1, (0, 0))

In [70]:
a.grid

array([[-1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [71]:
a.display_board()

 O |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   


In [72]:
a.play(1, (1,1))

In [73]:
a.display_board()

 O |   |   |   |   
---+---+---+---+---
   | X |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   


In [74]:
a.play(-1, (0,2))

In [75]:
a.play(1, (2,2))

In [76]:
a.display_board()

 O |   | O |   |   
---+---+---+---+---
   | X |   |   |   
---+---+---+---+---
   |   | X |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   


In [77]:
a.play(-1, (0, 1))

In [78]:
a.display_board()

 O | O | O |   |   
---+---+---+---+---
   | X |   |   |   
---+---+---+---+---
   |   | X |   |   
---+---+---+---+---
   |   |   |   |   
---+---+---+---+---
   |   |   |   |   
